// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "21d89e40-5505-4529-bf1a-fd48399e10f5";

const char SSID[]               = "VMup";    // Network SSID (name)
const char PASS[]               = "";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "C5fflOiVKF9eklE5YTb7roMsb";    // Secret device password



void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
